### ISSUE TITLE
To Do by Final Week

### ISSUE THREAD

**Issue by dustinn1** [rayyanshaji/comp424-nutrional-value#15]
- [x] Complete the design of some pages (home, goals, log in, etc.)
- [x] Implement remaining login providers like twittter (Dustin)
- [x] Add items to database when adding items
	- Need to update post route to accept custom json body
- [x] Work on goals page
	- Using chart.js https://www.chartjs.org
	- Probably need to have logs page completed first in order to get nutritions for have as data for the charts.
- [x] Add calendar system where clicking on a date will send you to /log/2020-4-13 for example
	- Probably will use and modify https://github.com/niinpatel/calendarHTML-Javascript (MIT license)
	- [x] Make responsive
- [x] Implement nutrition labels for each item
	- Not too sure how to do this efficiently at the moment
- [x] Calculate nutritions for each meal and total
- [x] Clean up javascript (if there is time - Dustin)
- [x] Validate food log adding
- [x] Add way to delete items from db (through POST route or somehow)

**Comment by Troche4** [comment]
The charts page is intended to show a plot of the user's past weight measurements. I.E. showing each time the user has weighed themselves in the last week, month, year, etc

**Comment by dustinn1** [comment]
As of 4/20:

- [ ] Calculate nutritions for each meal and total (!!!)
- [ ] Display last 10 or so weight data on top graph (!!!)
- [ ] Add rest of nutrition data and display on label
- [ ] Make goals page better responsive
- [ ] Add way to reset user data (logs and goals) (Low priority)
